#!/bin/bash

main() {
    clear
    echo -e "Welcome to the MacSploit Experience!"
    echo -e "Install Script Version 2.6"

    echo -e "Skipping License Check..."
    
    echo -e "Downloading Latest Roblox..."
    [ -f ./RobloxPlayer.zip ] && rm ./RobloxPlayer.zip
    robloxVersionInfo=$(curl -s "https://clientsettingscdn.roblox.com/v2/client-version/MacPlayer")
    versionInfo=$(curl -s "https://git.raptor.fun/main/version.json")
    
    mChannel=$(echo $versionInfo | jq -r ".channel")
    version=$(echo $versionInfo | jq -r ".clientVersionUpload")
    robloxVersion=$(echo $robloxVersionInfo | jq -r ".clientVersionUpload")
    
    if [ "$version" != "$robloxVersion" ] && [ "$mChannel" == "preview" ]; then
        curl -o "./RobloxPlayer.zip" "http://setup.rbxcdn.com/mac/$robloxVersion-RobloxPlayer.zip"
    else
        curl -o "./RobloxPlayer.zip" "http://setup.rbxcdn.com/mac/$version-RobloxPlayer.zip"
    fi
    
    echo -n "Installing Latest Roblox... "
    [ -d "/Applications/Roblox.app" ] && rm -rf "/Applications/Roblox.app"

    unzip -o -q "./RobloxPlayer.zip"
    mv ./RobloxPlayer.app /Applications/Roblox.app
    rm ./RobloxPlayer.zip
    echo -e "Done."

    echo -e "Downloading MacSploit..."
    curl -o "./MacSploit.zip" "https://git.raptor.fun/main/macsploit.zip"

    echo -n "Installing MacSploit... "
    unzip -o -q "./MacSploit.zip"
    echo -e "Done."

    echo -n "Updating Dylib..."
    if [ "$version" != "$robloxVersion" ] && [ "$mChannel" == "preview" ]; then
        curl -O "https://git.raptor.fun/preview/macsploit.dylib"
    else
        curl -O "https://git.raptor.fun/main/macsploit.dylib"
    fi
    
    echo -e " Done."
    echo -e "Patching Roblox..."
    mv ./macsploit.dylib "/Applications/Roblox.app/Contents/MacOS/macsploit.dylib"
    ./insert_dylib "/Applications/Roblox.app/Contents/MacOS/macsploit.dylib" "/Applications/Roblox.app/Contents/MacOS/RobloxPlayer" --strip-codesig --all-yes
    mv "/Applications/Roblox.app/Contents/MacOS/RobloxPlayer_patched" "/Applications/Roblox.app/Contents/MacOS/RobloxPlayer"
    rm -r "/Applications/Roblox.app/Contents/MacOS/RobloxPlayerInstaller.app"
    rm ./insert_dylib

    echo -n "Installing MacSploit App... "
    [ -d "/Applications/MacSploit.app" ] && rm -rf "/Applications/MacSploit.app"
    mv ./MacSploit.app /Applications/MacSploit.app
    rm ./MacSploit.zip
    
    touch ~/Downloads/ms-version.json
    echo $versionInfo > ~/Downloads/ms-version.json
    if [ "$version" != "$robloxVersion" ] && [ "$mChannel" == "preview" ]; then
        jq '.channel = "previewb"' ~/Downloads/ms-version.json > ~/Downloads/ms-version.json.tmp && mv ~/Downloads/ms-version.json.tmp ~/Downloads/ms-version.json
    fi
    
    echo -e "Done."
    echo -e "Install Complete! Developed by Nexus42!"
    exit
}

main
